# Crypto environment defualts
ENV_STARTING_BALANCE = 1e6
ENV_MAX_ACTION = 1e4
ENV_TRADING_FEE = 1e-2
ENV_HISTORY = 4
ENV_REWARD_SCALING = 1e-4
ENV_EPISODE_LENGTH = 8192
ENV_VECTORIZED = False
ENV_VECTORIZED_LENGTH = 4